apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: slack-netes
spec:
  selector:
    matchLabels:
      app: slack-netes
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: slack-netes
    spec:
      containers:
      - name: slack-netes
        image: darrenrose/slack-netes:latest
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
